(global-set-key "\C-x7" 'three-quarters-window)
(global-set-key (kbd "C-c g") 'magit-status)
(global-set-key [f7] 'call-last-kbd-macro)
(global-set-key (kbd "C-c j") 'imenu)
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "M-*") 'pop-tag-mark)
